// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL7Uv5K7DFuBJt4QP_c6RCbzX16Tu5Dm8',
    appId: '1:122532894782:web:7e78e02a1d7b9a2208d96f',
    messagingSenderId: '122532894782',
    projectId: 'message-7d3c5',
    authDomain: 'message-7d3c5.firebaseapp.com',
    storageBucket: 'message-7d3c5.appspot.com',
    measurementId: 'G-QCT90WKQZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwOvyfIMfIhK0dUfqKhvhZBNt9TcfA3-c',
    appId: '1:122532894782:android:6ef6bcd3b70a6dfd08d96f',
    messagingSenderId: '122532894782',
    projectId: 'message-7d3c5',
    storageBucket: 'message-7d3c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDrA-J01ueacmmjoCznmhXbSNnal4ByV0',
    appId: '1:122532894782:ios:f319a24f4cba588f08d96f',
    messagingSenderId: '122532894782',
    projectId: 'message-7d3c5',
    storageBucket: 'message-7d3c5.appspot.com',
    iosBundleId: 'com.example.renthive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDrA-J01ueacmmjoCznmhXbSNnal4ByV0',
    appId: '1:122532894782:ios:f319a24f4cba588f08d96f',
    messagingSenderId: '122532894782',
    projectId: 'message-7d3c5',
    storageBucket: 'message-7d3c5.appspot.com',
    iosBundleId: 'com.example.renthive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL7Uv5K7DFuBJt4QP_c6RCbzX16Tu5Dm8',
    appId: '1:122532894782:web:ee11d0d8a88e226c08d96f',
    messagingSenderId: '122532894782',
    projectId: 'message-7d3c5',
    authDomain: 'message-7d3c5.firebaseapp.com',
    storageBucket: 'message-7d3c5.appspot.com',
    measurementId: 'G-02B2FC2GJW',
  );
}
